### ISSUE TITLE
Add new projects

### ISSUE THREAD

**Issue by perminder-klair** [zeiq-co/zeiq-co#3]
- [x] Listme
- [x] Packrs
- [x] Zeiq Academy
- [x] Clip bucket TV app
- [x] Food bucket Android / iOS App
- [x] Nebula Design
- [x] Youngworks

**Comment by thisbutterfly** [comment]
Done with four of them. Will be needing screenshots for Listme, Clip Bucket TV app and 
  Food bucket Android / iOS App. @perminder-klair @animusarya

**Comment by thisbutterfly** [comment]
Added all of the listed projects.
