### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by manishamal98** [zeiq-co/zeiq-co#65]
- [x] Need to show the required message on contact form.
![image](https://user-images.githubusercontent.com/100751239/174975946-55497196-9201-41bf-9280-c30b30e1dfaf.png)

**Comment by dharmveer97** [comment]
Frontend is completed

@taniyaraina can you please share the logins of Mailchimp. Please let me know if you need my help to get the following.

- I need Mailchimp Chatid
- Need Audience Id of Mailchimp
- APi keys of mailchimp
