### ISSUE TITLE
Final Issues for Testing  - DUE Date:- Monday  3 / july / 2022

### ISSUE THREAD

**Issue by dharmveer97** [zeiq-co/zeiq-co#68]
Note: Test the full website and all the changes are completed. 

- [x] Test Website on Mobile responsive and desktop. Pages list is shown below

 - [x]  Home page
 - [x] Recent Projects 
 - [x] Our Projects
 - [x] All services page
 - [x] Blog Page
 - [x] About Page
 - [x] Contact Page
 - [x] Single Blog page 
 - [x] Single Service page
 - [x] Single Product page ( Project is same as product )
 - [x] Technologies Images and Single technology content and page.

- [x] Test all social links
- [x] Test Mailchimp on Contact form.
- [x] Test All SEO ---  meta tags and Open Graph title and description. [Use This website for testing](https://metatags.io)
- [x] Test Light House performance on incognito mode.
- [x] Test the Whole website image rendering speed.
- [x] Check all buttons on the Whole website. test whether all buttons are clickable or not.
- [x] Check Website faviicon. (It's showing on top of the browser)

Last Issue

- [ ] Test Website Sitemap after the site will push on live domain.

**Comment by dharmveer97** [comment]
If all the issues are completed please send an update to @perminder-klai  then. He will push the website on the Live domain.

**Comment by manishamal98** [comment]
- [x] Need to add content to the services development page. (@taniyaraina )
- [x] Drop down is not opening in mobile view (@dharmveer97 )
![Web capture_4-7-2022_122825_zeiq-co-git-v4-zeiq-dev vercel app](https://user-images.githubusercontent.com/100751239/177099072-f1ad9ac2-3ff3-47a0-9ab5-3c1f1b38e8f6.jpeg)

- [x] image isn't uploading.(khushiram website) (@dharmveer97 )

![Web capture_4-7-2022_14050_zeiq-co-git-v4-zeiq-dev vercel app](https://user-images.githubusercontent.com/100751239/177115218-ac04a868-d0ff-4eb8-9edd-a97464cd49c3.jpeg)

- [x] image is not showing when we do meta tag testing.
![Web capture_4-7-2022_15620_metatags io](https://user-images.githubusercontent.com/100751239/177127547-348ac56f-c579-4341-9aea-c013b9e675c2.jpeg)

- [x] Need to improve this one. 
![image](https://user-images.githubusercontent.com/100751239/177131790-c2a50952-459a-4085-9dab-16da1e7e5692.png)

**Comment by dharmveer97** [comment]
@taniyaraina  can you please check image rendering issues some paths are not correct in some files.
Please add correct paths in content and check the whole website paths too

**Comment by taniyaraina** [comment]
> If all the issues are completed please send an update to @perminder-klai then. He will push the website on the Live domain.

**Comment by taniyaraina** [comment]
> @taniyaraina can you please check image rendering issues some paths are not correct in some files. Please add correct paths in content and check the whole website paths too

@dharmveer97 I have crosschecked all the paths.

**Comment by dharmveer97** [comment]
> > @taniyaraina can you please check image rendering issues some paths are not correct in some files. Please add correct paths in content and check the whole website paths too
> 
> @dharmveer97 I have crosschecked all the paths.

can you please check the website URLs please match the URLs with the old website.
