### ISSUE TITLE
Final Feedback (Due date :- 8/07/2022)

### ISSUE THREAD

**Issue by manishamal98** [zeiq-co/zeiq-co#70]
- [x]  we should need to apply the auto slider here. (home page)
![image](https://user-images.githubusercontent.com/100751239/177532215-6e57518f-0355-4299-8175-14f36071d4da.png)

- [x] Need to change the background color of the image or apply any shadow to image. (work page)
![image](https://user-images.githubusercontent.com/100751239/177534234-556334f2-6dd3-470b-9b64-4dad639a8273.png)

**Comment by dharmveer97** [comment]
@manishamal98  can you please double-check this issue is completed. Please have a look and let me know if its done from your side.
